name = x_mobs
title = X Mobs
description = High-performance Luanti mobs mod featuring custom glTF animated bosses and entities
depends = x_mob_core
optional_depends = default, x_player_api, farming, vessels, tnt, flowers, everness
min_minetest_version = 5.17.0
author = SaKeL
